service: ${self:custom.app}-services

# TODO, Support for "package.include" and "package.exclude" will be removed in the next major release. Please use "package.patterns" instead
# package:
#   exclude:
#     - node_modules/**

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

# functions:

custom:
  app: ${opt:app, 'meli-challenge'}

resources: # CloudFormation template syntax
  Resources:
    AppInstanceSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group that allows the income trafic for the ec2 instance
        GroupName: ${self:service}-${self:provider.stage}-ec2-sg
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 5000
            ToPort: 5000
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 6000
            ToPort: 6000
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 8080
            ToPort: 8080
            CidrIp: 0.0.0.0/0
        Tags:
          - Key: stage
            Value: ${self:provider.stage}
          - Key: service
            Value: ${self:service}

    AppInstance:
      DependsOn:
        - AppInstanceSG
      Type: AWS::EC2::Instance
      Properties:
        # ImageId: ami-04cb4ca688797756f # Amazon Linux 3
        ImageId: ami-0f403e3180720dd7e # Amazon Linux 3

        KeyName: ec2-flask # This key pair must exist in the ec2 key pairs
        InstanceType: t2.micro
        SecurityGroupIds:
          - Ref: AppInstanceSG
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -x
            sudo yum update -y
            sudo yum install git -y
            cd /home && sudo git clone https://github.com/camiloRamirezVillegas/meli-challenge.git
            sudo yum install -y golang
            sudo yum install -y python3-pip
            sudo yum install -y nginx
            sudo pip install gunicorn
            cd /home/meli-challenge/flask && sudo pip install -r requirements.txt
            cd /home/meli-challenge/flask/app_flask && sudo bash env_bash.bash
            cd /home/meli-challenge/golang && sudo CGO_ENABLED=1 go build -v
            cd /home/meli-challenge/golang && sudo /home/meli-challenge/golang/meli-go &
            cd /home/meli-challenge/flask && gunicorn --bind 0.0.0.0:5000 run:app --log-level=debug --workers=3 --daemon
            sudo cp /home/meli-challenge/nginx/meli-nginx.conf /etc/nginx/conf.d/meli-nginx.conf
            sudo systemctl start nginx
            echo "Fin UserData script"
        Tags:
          - Key: stage
            Value: ${self:provider.stage}
          - Key: service
            Value: ${self:service}
        PropagateTagsToVolumeOnCreation: true
